# Generated by Django 6.0.3 on 2026-03-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0002_alter_endgame_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template", models.CharField(max_length=100)),
                ("queens", models.IntegerField()),
                ("rooks", models.IntegerField()),
                ("bishops", models.IntegerField()),
                ("knights", models.IntegerField()),
                ("wdl", models.IntegerField()),
            ],
        ),
    ]
