# Generated by Django 6.0.2 on 2026-03-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('Mate with Queen', 'Mate with Queen'), ('Mate with Rook', 'Mate with Rook'), ('Ladder Mate', 'Ladder Mate'), ('King and Pawn', 'King and Pawn'), ('King and Pawn Draw', 'King and Pawn Draw')], max_length=100)),
                ('fen', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
