# Generated by Django 6.0.3 on 2026-03-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endgame",
            name="template",
            field=models.CharField(
                choices=[
                    ("mate_with_queen", "mate_with_queen"),
                    ("mate_with_rook", "mate_with_rook"),
                    ("ladder_mate", "ladder_mate"),
                    ("king_and_pawn", "king_and_pawn"),
                    ("king_and_pawn_draw", "king_and_pawn_draw"),
                ],
                max_length=100,
            ),
        ),
    ]
